### ISSUE TITLE
When dragging a Skill by the image, Firefox attempts to drag the image with the skill container

### ISSUE THREAD

**Issue by sam-cross** [MaxAltena/maxaltena.com#87]
Apparently the `draggable` attribute can be set in the HTML to avoid this!

Not sure quite how I found this repo but I LOVE the site. It's so creative.

**Comment by MaxAltena** [comment]
Hey Sam!

First of all, great to hear that you love the website! Secondly, thanks for creating an issue for this. And last but not least, I addressed this issue for now (c4e274c765f76ba6e78eff2fdceec8928a954e44) like you said. I was already planning on redo'ing the skills section on the website to be a bit more interactive/fun, as that was the intention of the section itself.
